### exclude nvim config ###
# [".config/nvim"]
# type = "archive"
# url = "https://github.com/liaohui5/nvim/archive/refs/heads/main.zip"
# exact = true
# stripComponents = 1
# refreshPeriod = "168h"

# include vim config
[".vim"]
type = "archive"
url = "https://github.com/liaohui5/light-vim-starter/archive/refs/heads/main.zip"
exact = true
stripComponents = 1
refreshPeriod = "168h"
