#!/usr/bin/env zsh
################################################################
# load zimfw if exists
################################################################
ZIM_HOME="${HOME}/.zim"
## auto download zimfw if missing
# if [[ ! -e \${ZIM_HOME}/zimfw.zsh ]]; then
#   if (( \${+commands[curl]} )); then
#     curl -fsSL --create-dirs -o \${ZIM_HOME}/zimfw.zsh \\
#         https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
#   else
#     mkdir -p \${ZIM_HOME} && wget -nv -O \${ZIM_HOME}/zimfw.zsh \\
#         https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
#   fi
# fi
if [[ -d "${ZIM_HOME}" ]]; then
  # set zsh options
  setopt HIST_IGNORE_ALL_DUPS

  # set keybindings
  bindkey -v

  # set wordchars options
  WORDCHARS=${WORDCHARS//[\/]}

  # plugin settings
  ZSH_AUTOSUGGEST_MANUAL_REBIND=1
  ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

  # init zimfw
  if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
    source ${ZIM_HOME}/zimfw.zsh init
  fi

  # load zimfw
  source ${ZIM_HOME}/init.zsh
fi

################################################################
# define helper functions
################################################################
# ~/.zsh-scripts
ZSH_SCRIPTS_DIR="$HOME/.zsh-scripts"

# MacOS language locale
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# for some config files
export XDG_CONFIG_HOME="$HOME/.config"

# keybindings
bindkey '^K' up-line-or-search
bindkey '^J' down-line-or-search
bindkey '^H' backward-char
bindkey '^L' forward-char

# check command exists
function has-command() {
  if command -v "$1" >/dev/null; then
    return 0
  else
    return 1
  fi
}

# check command exists and alias it
# safe-alias <alias> <cmd>
function safe-alias() {
  local alias="$1"
  local cmd="$2"
  if command -v "$cmd" >/dev/null; then
    alias "$alias"="$cmd"
  fi
}

# check file exists
function file-exists() {
    if [[ -f "$1" ]]; then
        return 0
    else
        return 1
    fi
}

# source file if file exists
function safe-source() {
    target_file="$1"
    if file-exists "$target_file"; then
        source "$target_file"
    else
        echo "File: $target_file does not exist"
    fi
}

# add local path to system path env
function append-path() {
  local new_path="$1"
  if [[ -d "$new_path" ]]; then
    case ":$PATH:" in
      *:"$new_path":*)
        ;;
      *)
        export PATH="$PATH:$new_path"
        ;;
    esac
  fi
}


################################################################
# editor
################################################################
# https://github.com/neovim/neovim
if has-command 'nvim'; then
  export EDITOR='nvim'
elif has-command 'vim'; then
  export EDITOR='vim'
else
  export EDITOR='vi'
fi

################################################################
# PATH
################################################################
# homebrew
# https://brew.sh/
if has-command 'brew'; then
  export PATH="/usr/local/bin:$PATH"
  safe-source "$ZSH_SCRIPTS_DIR/homebrew.zsh"
fi

# zoxide
# https://github.com/ajeetdsouza/zoxide
if has-command 'zoxide'; then
  eval "$(zoxide init zsh)"
fi

# fzf
# https://github.com/junegunn/fzf
if has-command 'fzf'; then
  eval "$(fzf --zsh)"
fi

# rustup
# https://rustup.rs/
safe-source "$HOME/.cargo/env"

# starship
# https://starship.rs/zh-CN/
if has-command 'starship'; then
  eval "$(starship init zsh)"
  export STARSHIP_CONFIG="${HOME}/.config/starship/config.toml"
fi

# yazi
# https://yazi-rs.github.io/
if has-command 'yazi'; then
  function fm() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
      builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
  }
fi

# mise
if [[ -f "$HOME/.cargo/bin/mise" ]]; then
  eval "$(~/.cargo/bin/mise activate zsh)"
fi

# goproxy
if has-command 'go'; then
  export GOPROXY="https://goproxy.cn/,https://mirrors.aliyun.com/goproxy/,https://goproxy.bj.bcebos.com,direct"
fi

# uv
# https://docs.astral.sh/uv/getting-started
if has-command 'uv'; then
  append-path "$HOME/.local/bin"
fi

# pnpm
# https://pnpm.io/
if has-command 'pnpm'; then
  export PNPM_HOME="$HOME/.pnpm_store"
  append-path $PNPM_HOME
  append-path "${PNPM_HOME}/bin"
fi

################################################################
# load zsh scripts
################################################################
# zsh scripts saved directory
safe-source "$HOME/.zprofile"
safe-source "$ZSH_SCRIPTS_DIR/alias.zsh"
safe-source "$ZSH_SCRIPTS_DIR/proxy.zsh"
safe-source "$ZSH_SCRIPTS_DIR/ssh-manager.zsh"

# load software specific zsh scripts
if has-command VBoxManage; then
    safe-source "$ZSH_SCRIPTS_DIR/vbox-manager.zsh"
fi
if has-command vmrun; then
    safe-source "$ZSH_SCRIPTS_DIR/vmware-manager.zsh"
fi
if has-command zellij; then
    safe-source "$ZSH_SCRIPTS_DIR/zellij.zsh"
fi
