##############################################################################################
# lazygit 配置
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_zh-CN.md
##############################################################################################
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  showRootItemInFileTree: false
  sidePanelWidth: 0.5
  showRandomTip: false
  border: single
  showIcons: true
  showFileIcons: true
  commitHashLength: 6
git:
  autoFetch: true
  autoRefresh: true
  parseEmoji: true

# 快捷键绑定:
customCommands:
  # 打开默认的快捷键文档
  - key: "<c-k>"
    description: "Open keybindings docs"
    context: "global"
    command: "open -u 'https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_zh-CN.md'"

  # 集成 czg 命令, 生成符合规范的提交信息
  # 注意需要安装命令 npm i -g czg
  # docs: https://cz-git.qbb.sh/zh/
  - key: "<c-c>"
    description: "Generate commit use czg"
    context: "files"
    command: "czg"
    output: terminal

  # 集成 czg ai 命令, 使用AI快速生成提交模板
  # 注意需要先配置请求 api 需要的相关信息
  # docs: https://cz-git.qbb.sh/zh/cli/ai
  - key: "<c-e>"
    description: "Generate commit using ai"
    command: "czg ai"
    context: "files"
    output: terminal
