#!/usr/bin/env bash
# ╭──────────────────────────────────────────────────────────────────────────────╮ #
# │ skhd                                                                         │ #
# │ example: https://github.com/koekeishiya/yabai/blob/master/examples/skhdrc    │ #
# ╰──────────────────────────────────────────────────────────────────────────────╯ #

# ╭──────────────────────────────────────────────────────────────────────────────╮
# │ <ESC>auto switch input method                                                │
# ╰──────────────────────────────────────────────────────────────────────────────╯
0x35 -> : im-select com.apple.keylayout.ABC

# ╭──────────────────────────────────────────────────────────────────────────────╮
# │ launcher                                                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
# list all applications: sudo find / -iname "*.app"
# show app BundleId    : mdls -name kMDItemCFBundleIdentifier /Applications/Safari.app
# show skhd keybindings: skhd -o
alt - 1: open -b "com.apple.finder"                     # Finder
alt - 2: open -b "org.alacritty" --args -e yazi ~       # open alacritty and execute yazi command
alt - 3: open -b "com.github.wez.wezterm"               # wezterm
alt - 4: open -b "org.mozilla.thunderbird"              # open thunderbird
alt - 5: open -b "com.tencent.xinWeChat"                # wechat
alt - 6: open -b "com.tencent.qq"                       # qq
alt - 7: open -b "org.alacritty" --args -e zellij       # Alacritty & zellij
alt - 8: open -b "net.kovidgoyal.kitty"                 # kitty
alt - 9: open -a "Launchpad"                            # macOS launchpad
alt - 0: open -b "org.chromium.Thorium"                 # Thorium(Chromium fork)
# alt - 0: open -b "com.google.chrome"                    # Google Chrome
# alt - 0: open -b "org.mozilla.firefox"                  # firefox

